# Project information
site_name: Maude Shen
site_description: 沈孟學 Maude Shen
site_author: Maude Shen

site_url: https://maudes.github.io/


# Copyright
copyright: "&copy; 2025"

plugins:
  - tags
  - search

theme:
  name: material
  favicon: favicon.ico
  language: en
  font:
    text: Muli
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - tables
    - adomination


  features:
    - navigation.instant
    - navigation.footer
    - search.highlight
    - content.tabs.link

extra_css:
  - assets/css/extra.css


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maudes
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/meng-hsueh-shen
    - icon: fontawesome/brands/medium
      link: https://medium.com/@maudeshen

nav:
  - ABOUT ME: index.md
  - EXPERIENCE: experience.md
  - EDUCATION & SKILLS: education_skills.md
  - PORTFOLIO:
      - Overview: portfolio.md
      - fCC Hackathon "DailyDoes" Web App: projects/dailydose.md 
      - WiZ Local Test Script: projects/wiz_local.md
      - WiZ Smart light: projects/wiz.md
      - iGaming: projects/igaming.md
      - SALASUSU: projects/salasusu.md
      - SmallSomebody: projects/smallsomebody.md



